// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace APS.NUnit.Ext.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class Fake : APS.NUnit.Ext.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.FakeJob.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using System;\r\n    using System.Data.Entity;\r\n    using System.Data.Enti" +
                    "ty.Infrastructure;\r\n    using System.Data.Entity.Core.Objects;\r\n    using System" +
                    ".Linq;\r\n    \r\n    public partial class ");
            
            #line 14 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.FakeJob.TypeName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 14 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.IDbContextJob.TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 16 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.FakeJob.TypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n\t\t\t");
            
            #line 18 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"

			foreach(var property in Params.DbContextType.DbSetProperties)
			{
			
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 22 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new FakeDbSet<");
            
            #line 22 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.GetGenericArguments()[0].Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 23 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"

			}
			
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n\t\t");
            
            #line 28 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"

		foreach(var property in Params.DbContextType.DbSetProperties)
		{
		
            
            #line default
            #line hidden
            this.Write("\t\tpublic virtual DbSet<");
            
            #line 32 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PropertyType.GetGenericArguments()[0].Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 32 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\t\t");
            
            #line 33 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"

		}
		
            
            #line default
            #line hidden
            this.Write("\r\n\t\t");
            
            #line 37 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"

		foreach(var method in Params.DbContextType.AvailableMethods)
		{
		string returnType = "";
		if(method.ReturnType != null)
			returnType = method.ReturnType.Name;
		else
			returnType = "void";
		
            
            #line default
            #line hidden
            this.Write("\t\tpublic partial ");
            
            #line 46 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 46 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 46 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("BLANK"));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t");
            
            #line 47 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Fake.tt"

		}
		
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
