// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace APS.NUnit.Ext.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class IDbContext : APS.NUnit.Ext.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.IDbContextJob.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using System;\r\n    using System.Data.Entity;\r\n    using System.Data.Enti" +
                    "ty.Infrastructure;\r\n    using System.Data.Entity.Core.Objects;\r\n    using System" +
                    ".Linq;\r\n    \r\n    public partial interface ");
            
            #line 14 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.IDbContextJob.TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n\t\t");
            
            #line 16 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"

		foreach(var property in Params.DbContextType.DbSetProperties)
		{
		
            
            #line default
            #line hidden
            this.Write("        DbSet<");
            this.Write("> ");
            this.Write(" { get; set; }\r\n\t\t");
            
            #line 21 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"

		}
		
            
            #line default
            #line hidden
            this.Write("    \r\n\t\t");
            
            #line 25 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"

		foreach(var method in Params.DbContextType.AvailableMethods)
		{
		
            
            #line default
            #line hidden
            this.Write("\t\t");
            this.Write(" ");
            this.Write("(");
            this.Write(");\r\n\t\t");
            
            #line 30 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\IDbContext.tt"

		}
		
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
