// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace APS.NUnit.Ext.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class Provider : APS.NUnit.Ext.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.ProviderJob.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using System;\r\n    using System.Data.Entity;\r\n    using System.Data.Enti" +
                    "ty.Infrastructure;\r\n\tusing APS.NUnit.Ext;\r\n    \r\n    public partial class ");
            
            #line 13 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.ProviderJob.TypeName));
            
            #line default
            #line hidden
            this.Write(" : BaseProvider<");
            
            #line 13 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.IDbContextJob.TypeName));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public override ");
            
            #line 15 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.IDbContextJob.TypeName));
            
            #line default
            #line hidden
            this.Write(" NewFake()\r\n        {\r\n            return new ");
            
            #line 17 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.FakeJob.TypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n        }\r\n        \r\n        public override ");
            
            #line 20 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.IDbContextJob.TypeName));
            
            #line default
            #line hidden
            this.Write(" NewReal()\r\n        {\r\n            return new ");
            
            #line 22 "C:\Users\Alex\Source\APS.NUnit.Ext\APS.NUnit.Ext\APS.NUnit.Ext\Templates\Provider.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Params.DbContextType.Type.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
