//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.NUnit.Ext.Example.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial interface ILocalDatabaseEntities1
    {
        DbSet<Address> Addresses { get; set; }
        DbSet<Person> People { get; set; }
        DbSet<View> Views { get; set; }
    
        [DbFunction("LocalDatabaseEntities1", "Function")]
        IQueryable<Function_Result> Function(Nullable<int> param1, string param2);
    
        ObjectResult<Nullable<int>> Procedure(Nullable<int> param1);
    }
}
