//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Person
{
    public Person()
    {
        this.Addresses = new HashSet<Address>();
    }

    public int Id { get; set; }
    public string First { get; set; }
    public string Last { get; set; }
    public System.DateTime DateOfBirth { get; set; }

    public virtual ICollection<Address> Addresses { get; set; }
}
