//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace APS.NUnit.Ext.Example.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILocalDatabaseEntities1Provider : BaseProvider<ILocalDatabaseEntities1>
    {
        public override ILocalDatabaseEntities1 NewFake()
        {
            return new StubLocalDatabaseEntities1();
        }
        
        public override ILocalDatabaseEntities1 NewReal()
        {
            return new LocalDatabaseEntities1();
        }
    }
}
