//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.NUnit.Ext.Example.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using APS.NUnit.Ext;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StubLocalDatabaseEntities1 : ILocalDatabaseEntities1
    {
        public StubLocalDatabaseEntities1()
        {
            Addresses = new FakeDbSet<Address>();
            People = new FakeDbSet<Person>();
            Views = new FakeDbSet<View>();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<View> Views { get; set; }


        public IQueryable<Function_Result> Function(int? param1, string param2)
        {
            throw new NotImplementedException();
        }

        public ObjectResult<int?> Procedure(int? param1)
        {
            throw new NotImplementedException();
        }
    }
}
