//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.NUnit.Ext.Example.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using APS.NUnit.Ext;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StubLocalDatabaseEntities1 : ILocalDatabaseEntities1
    {
        public StubLocalDatabaseEntities1()
        {
            Addresses = new StubDbSet<Address>();
            People = new StubDbSet<Person>();
            Views = new StubDbSet<View>();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<View> Views { get; set; }
    }
}
